# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        ./fade version
        FADE_PROJECT_NAME="fade" FADE_PROJECT_DESC="Fully Automated Distribution enhanced" FADE_PROJECT_RUN="null" FADE_PROJECT_VERSION="0.0.1" FADE_PROJECT_DEPENDS="bash" FADE_MAINTAINER_NAME="Fully Automated Distribution enhanced Developers" FADE_MAINTAINER_MAIL="fade-linux@protonmail.com" FADE_PROJECT_WWW="https://fade-linux.github.io/" FADE_PROJECT_BOOT="0" ./fade init
        rm fadework/usr/bin/fade
        cp ./fade fadework/usr/bin/fade
        ./fade builddeb
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: project-dist.deb
